"""Tests for scaffold file writing helpers."""

from __future__ import annotations

import pytest

from optiprofiler_agent.advisor.scaffold_file import write_scaffold_file


def test_write_scaffold_file_dry_run_does_not_touch_disk(tmp_path):
    target = tmp_path / "feature.py"

    result = write_scaffold_file(target, "print('hello')\n", mode="new", dry_run=True)

    assert result.dry_run is True
    assert result.changed is True
    assert result.diff.startswith("--- ")
    assert "\n+++ " in result.diff
    assert "\n@@ " in result.diff
    assert "Generated by opagent scaffold_feature" in result.diff
    assert not target.exists()


def test_write_scaffold_file_creates_new_file(tmp_path):
    target = tmp_path / "feature.py"

    result = write_scaffold_file(target, "print('hello')\n", mode="new", dry_run=False, label="demo")

    assert result.changed is True
    text = target.read_text(encoding="utf-8")
    assert text.startswith("#!/usr/bin/env python\n# Generated by opagent scaffold_feature: demo")
    assert "print('hello')" in text


def test_write_scaffold_file_new_mode_rejects_existing_file(tmp_path):
    target = tmp_path / "feature.py"
    target.write_text("old\n", encoding="utf-8")

    with pytest.raises(FileExistsError):
        write_scaffold_file(target, "new\n", mode="new", dry_run=True)


def test_write_scaffold_file_appends_with_import_dedup(tmp_path):
    target = tmp_path / "feature.py"
    target.write_text("import numpy as np\n\nOLD = 1\n", encoding="utf-8")
    body = "import numpy as np\nfrom optiprofiler import benchmark\n\nNEW = 2\n"

    result = write_scaffold_file(target, body, mode="append", dry_run=False)

    text = target.read_text(encoding="utf-8")
    assert result.changed is True
    assert text.count("import numpy as np") == 1
    assert "from optiprofiler import benchmark" in text
    assert "OLD = 1" in text
    assert "NEW = 2" in text


def test_write_scaffold_file_auto_appends_existing_file(tmp_path):
    target = tmp_path / "feature.py"
    target.write_text("A = 1\n", encoding="utf-8")

    result = write_scaffold_file(target, "B = 2\n", mode="auto", dry_run=False)

    assert result.mode == "append"
    assert target.read_text(encoding="utf-8").endswith("B = 2\n")
