"""Generate and smoke-test staged custom problem-library wrappers."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from textwrap import dedent
from typing import Any

from optiprofiler_agent.advisor.plib_scanner import PlibScanEvidence, scan_local_plib


@dataclass(frozen=True)
class PlibScaffoldResult:
    """Generated staged wrapper files for one custom problem library."""

    staging_dir: Path
    library_name: str
    tools_path: Path
    copied_files: list[Path]
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data["staging_dir"] = str(self.staging_dir)
        data["tools_path"] = str(self.tools_path)
        data["copied_files"] = [str(path) for path in self.copied_files]
        return data

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, ensure_ascii=False)


@dataclass(frozen=True)
class PlibSmokeResult:
    """Result from running a staged wrapper smoke test."""

    ok: bool
    returncode: int
    stdout: str
    stderr: str
    tested_problem_names: list[str]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, ensure_ascii=False)


def _safe_lib_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", name).strip("_").lower()
    if not cleaned:
        raise ValueError("library_name must contain at least one alphanumeric character")
    if cleaned[0].isdigit():
        cleaned = f"plib_{cleaned}"
    return cleaned


def _find_primary_python(evidence: PlibScanEvidence) -> str | None:
    candidates = [
        item.path for item in evidence.files
        if item.path.endswith(".py") and (
            item.path in evidence.loader_hints
            or item.path in evidence.selector_hints
            or "single_problem_loader" in item.hints
            or "selector_function" in item.hints
        )
    ]
    if candidates:
        return sorted(candidates, key=lambda p: (p.count("/"), p))[0]
    py_files = [item.path for item in evidence.files if item.path.endswith(".py")]
    return sorted(py_files, key=lambda p: (p.count("/"), p))[0] if py_files else None


def _find_probinfo_csv(evidence: PlibScanEvidence) -> str | None:
    for item in evidence.files:
        if item.path.endswith(".csv") and "problem_name" in item.columns:
            return item.path
    return None


def _render_tools_py(lib: str, primary_rel: str, has_source_selector: bool, csv_name: str | None) -> str:
    select_impl = (
        "        if hasattr(module, 'find_problems'):\n"
        "            return list(module.find_problems(options))\n"
        "        if hasattr(module, 'select_problems'):\n"
        "            return list(module.select_problems(options))\n"
        "        if hasattr(module, 'select'):\n"
        "            return list(module.select(options))\n"
    ) if has_source_selector else ""

    csv_fallback = ""
    if csv_name:
        csv_fallback = f"""
        csv_path = Path(__file__).with_name({csv_name!r})
        if csv_path.exists():
            return _select_from_csv(csv_path, options)
"""

    return dedent(f'''\
    """OptiProfiler custom problem-library wrapper for {lib}.

    Generated by opagent. Review field mappings before using on a large run.
    """

    from __future__ import annotations

    import csv
    import importlib.util
    from pathlib import Path

    import numpy as np
    from optiprofiler import Problem


    _SOURCE_FILE = Path(__file__).resolve().parent / {primary_rel!r}


    def _load_source_module():
        spec = importlib.util.spec_from_file_location("{lib}_source", _SOURCE_FILE)
        if spec is None or spec.loader is None:
            raise ImportError(f"Cannot import source module at {{_SOURCE_FILE}}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module


    def _as_problem(native, problem_name):
        if isinstance(native, Problem):
            return native
        if callable(native) and not hasattr(native, "fun"):
            return Problem(native, np.zeros(1), name=problem_name)
        if hasattr(native, "fun") and hasattr(native, "x0"):
            x0 = np.asarray(native.x0, dtype=float).reshape(-1)
            xl = np.asarray(getattr(native, "xl", -np.inf * np.ones_like(x0)), dtype=float).reshape(-1)
            xu = np.asarray(getattr(native, "xu", np.inf * np.ones_like(x0)), dtype=float).reshape(-1)
            fun = lambda x: float(native.fun(np.asarray(x, dtype=float)))
            return Problem(fun, x0, name=problem_name, xl=xl, xu=xu)
        raise TypeError(
            "Source loader must return an optiprofiler.Problem, a callable objective, "
            "or an object with .fun and .x0."
        )


    def {lib}_load(problem_name, *args, **kwargs):
        """Load one source problem and convert it to ``optiprofiler.Problem``."""
        module = _load_source_module()
        for name in ("load_problem", "get_problem", "import_problem", "make_problem", "load"):
            loader = getattr(module, name, None)
            if callable(loader):
                return _as_problem(loader(problem_name, *args, **kwargs), problem_name)
        raise AttributeError("No source loader found: expected load_problem/get_problem/import_problem/make_problem/load")


    def {lib}_select(options):
        """Return problem names matching OptiProfiler-style selector options."""
        options = dict(options or {{}})
        module = _load_source_module()
{select_impl}{csv_fallback}
        raise AttributeError("No source selector or probinfo CSV found")


    def _select_from_csv(path, options):
        allowed_ptype = set(str(options.get("ptype", "ubln")))
        mindim = int(options.get("mindim", 1))
        maxdim_raw = options.get("maxdim", float("inf"))
        maxdim = float("inf") if maxdim_raw in (None, "inf", "Inf") else int(maxdim_raw)
        excluded = set(options.get("excludelist", []) or [])
        names = []
        with open(path, newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                name = row.get("problem_name", "")
                if not name or name in excluded:
                    continue
                ptype = row.get("ptype", "u")
                try:
                    dim = int(float(row.get("dim", "1") or 1))
                except ValueError:
                    dim = 1
                if ptype in allowed_ptype and mindim <= dim <= maxdim:
                    names.append(name)
        return names
    ''')


def scaffold_plib_wrapper(
    src_dir: str | Path,
    library_name: str | None = None,
    *,
    staging_dir: str | Path | None = None,
) -> PlibScaffoldResult:
    """Generate a staged Python custom problem-library wrapper."""
    evidence = scan_local_plib(src_dir, library_name)
    lib = _safe_lib_name(evidence.library_name)
    source_root = Path(evidence.source_dir)
    primary_rel = _find_primary_python(evidence)
    if not primary_rel:
        raise ValueError("No Python source file found; M4b Stage 2 currently supports Python source libraries")

    stage = Path(staging_dir).expanduser().resolve() if staging_dir else source_root / ".opagent_scaffold" / lib
    stage.mkdir(parents=True, exist_ok=True)

    primary_src = source_root / primary_rel
    primary_dst = stage / primary_rel
    primary_dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(primary_src, primary_dst)
    copied = [primary_dst]

    csv_rel = _find_probinfo_csv(evidence)
    csv_name = None
    if csv_rel:
        csv_src = source_root / csv_rel
        csv_name = f"probinfo_{lib}.csv"
        csv_dst = stage / csv_name
        shutil.copy2(csv_src, csv_dst)
        copied.append(csv_dst)

    has_source_selector = bool(evidence.selector_hints)
    tools_path = stage / f"{lib}_tools.py"
    tools_path.write_text(
        _render_tools_py(lib, primary_rel, has_source_selector, csv_name),
        encoding="utf-8",
    )

    warnings: list[str] = []
    if not csv_rel and not has_source_selector:
        warnings.append("No selector hint or probinfo CSV found; generated wrapper may not select problems.")
    if evidence.pickle_risk_hints:
        warnings.append("Potential pickle hazards: " + ", ".join(evidence.pickle_risk_hints))

    return PlibScaffoldResult(
        staging_dir=stage,
        library_name=lib,
        tools_path=tools_path,
        copied_files=copied,
        warnings=warnings,
    )


def _smoke_script(lib: str, stage: Path, max_problems: int) -> str:
    return dedent(f"""\
    import importlib.util
    import json
    import pickle
    import sys
    from pathlib import Path

    import numpy as np

    stage = Path({str(stage)!r})
    sys.path.insert(0, str(stage))
    tools_path = stage / {f'{lib}_tools.py'!r}
    spec = importlib.util.spec_from_file_location({f'{lib}_tools'!r}, tools_path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    names = list(getattr(module, {f'{lib}_select'!r})({{'mindim': 1, 'maxdim': 20}}))
    names = names[:{max_problems}]
    if not names:
        raise AssertionError('selector returned no problem names')
    tested = []
    for name in names:
        problem = getattr(module, {f'{lib}_load'!r})(name)
        value = float(problem.fun(problem.x0))
        if not np.isfinite(value):
            raise AssertionError(f'non-finite f(x0) for {{name}}: {{value}}')
        pickle.dumps(problem.name)
        tested.append(name)
    print(json.dumps({{'tested_problem_names': tested}}))
    """)


def smoke_test_plib_wrapper(
    staging_dir: str | Path,
    library_name: str,
    *,
    max_problems: int = 3,
    timeout: int = 30,
) -> PlibSmokeResult:
    """Subprocess smoke-test a staged wrapper."""
    lib = _safe_lib_name(library_name)
    stage = Path(staging_dir).expanduser().resolve()
    proc = subprocess.run(
        [sys.executable, "-c", _smoke_script(lib, stage, max_problems)],
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    tested: list[str] = []
    if proc.stdout.strip():
        try:
            data = json.loads(proc.stdout.strip().splitlines()[-1])
            tested = list(data.get("tested_problem_names", []))
        except json.JSONDecodeError:
            tested = []
    return PlibSmokeResult(
        ok=proc.returncode == 0,
        returncode=proc.returncode,
        stdout=proc.stdout,
        stderr=proc.stderr,
        tested_problem_names=tested,
    )
