"""Safe file-writing helpers for generated scaffold code."""

from __future__ import annotations

import difflib
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ScaffoldFileWriteResult:
    """Result of staging or applying a scaffold file write."""

    path: Path
    mode: str
    dry_run: bool
    changed: bool
    diff: str
    message: str

    def to_markdown(self) -> str:
        status = "Preview" if self.dry_run else "Written"
        md = (
            f"## Scaffold File {status}\n\n"
            f"- Path: `{self.path}`\n"
            f"- Mode: `{self.mode}`\n"
            f"- Changed: `{self.changed}`\n\n"
            f"{self.message}"
        )
        if self.diff:
            md += f"\n\n```diff\n{self.diff.rstrip()}\n```"
        return md


def _normalise_mode(mode: str, path: Path) -> str:
    value = (mode or "auto").strip().lower()
    if value == "auto":
        return "append" if path.exists() else "new"
    if value not in {"new", "append", "overwrite"}:
        raise ValueError("mode must be one of: auto, new, append, overwrite")
    return value


def _with_file_header(body: str, label: str = "") -> str:
    text = body.rstrip() + "\n"
    if text.startswith("#!"):
        return text
    suffix = f": {label.strip()}" if label.strip() else ""
    return f"#!/usr/bin/env python\n# Generated by opagent scaffold_feature{suffix}\n\n{text}"


def _split_imports(lines: list[str]) -> tuple[list[str], list[str]]:
    imports: list[str] = []
    rest = lines[:]
    while rest and not rest[0].strip():
        imports.append(rest.pop(0))
    while rest and (rest[0].startswith("import ") or rest[0].startswith("from ")):
        imports.append(rest.pop(0))
        while rest and not rest[0].strip():
            imports.append(rest.pop(0))
    return imports, rest


def _append_with_import_dedup(existing: str, body: str) -> str:
    existing_lines = existing.splitlines()
    body_lines = body.rstrip().splitlines()
    body_imports, body_rest = _split_imports(body_lines)
    existing_imports = {line.strip() for line in existing_lines if line.startswith(("import ", "from "))}
    filtered_imports = [
        line for line in body_imports
        if not line.strip() or line.strip() not in existing_imports
    ]
    append_lines = filtered_imports + body_rest
    append_text = "\n".join(line for line in append_lines).strip()
    if not append_text:
        return existing.rstrip() + "\n"
    separator = "\n\n\n" if existing.strip() else ""
    return existing.rstrip() + separator + append_text + "\n"


def _make_diff(path: Path, before: str, after: str) -> str:
    diff_lines = list(
        difflib.unified_diff(
            before.splitlines(),
            after.splitlines(),
            fromfile=f"{path} (before)",
            tofile=f"{path} (after)",
            lineterm="",
        )
    )
    return "\n".join(diff_lines) + ("\n" if diff_lines else "")


def write_scaffold_file(
    path: str | Path,
    body: str,
    *,
    mode: str = "auto",
    dry_run: bool = True,
    label: str = "",
) -> ScaffoldFileWriteResult:
    """Preview or apply a scaffold file write.

    ``mode="auto"`` creates a new file when the target does not exist and
    appends to an existing file. ``dry_run=True`` returns the exact unified
    diff without touching disk; callers should use it for the confirmation
    step before applying a write.
    """
    if not str(path).strip():
        raise ValueError("path is required")
    if not body.strip():
        raise ValueError("body is required")

    target = Path(path).expanduser().resolve()
    resolved_mode = _normalise_mode(mode, target)
    before = target.read_text(encoding="utf-8") if target.exists() else ""

    if resolved_mode == "new":
        if target.exists():
            raise FileExistsError(f"{target} already exists; use append or overwrite")
        after = _with_file_header(body, label=label)
    elif resolved_mode == "overwrite":
        after = _with_file_header(body, label=label)
    else:
        after = _append_with_import_dedup(before, body)

    changed = before != after
    diff = _make_diff(target, before, after) if changed else ""

    if not dry_run and changed:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(after, encoding="utf-8")

    if dry_run:
        message = "No file was changed. Re-run with `dry_run=False` to apply this diff."
    elif changed:
        message = "File updated."
    else:
        message = "No changes were needed."

    return ScaffoldFileWriteResult(
        path=target,
        mode=resolved_mode,
        dry_run=dry_run,
        changed=changed,
        diff=diff,
        message=message,
    )
